services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
