services:
  backendv1:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app_network
    volumes:
      - pdfdata:/app/pdfs

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backendv2:
    build:
      context: ./backendv2    
    container_name: backendv2
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - hf_cache:/root/.cache/huggingface  
      - ./backendv2:/app

  backendv3:
    build: ./backendv3
    container_name: backendv3
    ports: 
      - "8001:8001"
    networks:
      - app_network   

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backendv1
      - backendv2
      - backendv3

networks:
  app_network:

volumes:
  pdfdata:
  hf_cache:
  redis_data:
